// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJC3Ni7GFXBtyd8XVXjDKWJnMo7cuCXJ0',
    appId: '1:966860415762:web:5681a208eaa37d1f04c9cb',
    messagingSenderId: '966860415762',
    projectId: 'projetwave-fdf80',
    authDomain: 'projetwave-fdf80.firebaseapp.com',
    storageBucket: 'projetwave-fdf80.firebasestorage.app',
    measurementId: 'G-9H1XCHSNXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-xb2GpcFDdUHDdqz3Zoq43riLx1Je14',
    appId: '1:966860415762:android:f970aac8eb5047db04c9cb',
    messagingSenderId: '966860415762',
    projectId: 'projetwave-fdf80',
    storageBucket: 'projetwave-fdf80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsX39Ivs4uvrlvaDt8iGtIdWDrCsFPf5Y',
    appId: '1:966860415762:ios:f9e3402c46c24eda04c9cb',
    messagingSenderId: '966860415762',
    projectId: 'projetwave-fdf80',
    storageBucket: 'projetwave-fdf80.firebasestorage.app',
    iosBundleId: 'com.back.flutter3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsX39Ivs4uvrlvaDt8iGtIdWDrCsFPf5Y',
    appId: '1:966860415762:ios:f9e3402c46c24eda04c9cb',
    messagingSenderId: '966860415762',
    projectId: 'projetwave-fdf80',
    storageBucket: 'projetwave-fdf80.firebasestorage.app',
    iosBundleId: 'com.back.flutter3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJC3Ni7GFXBtyd8XVXjDKWJnMo7cuCXJ0',
    appId: '1:966860415762:web:84841310b75813e004c9cb',
    messagingSenderId: '966860415762',
    projectId: 'projetwave-fdf80',
    authDomain: 'projetwave-fdf80.firebaseapp.com',
    storageBucket: 'projetwave-fdf80.firebasestorage.app',
    measurementId: 'G-S6E41XXF8H',
  );
}
